import type { Metadata } from "next";
import { MyNavbar } from "./ui/MyNavbar";
import { Inter } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

// Is this used
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-screen-lg mx-auto">
          <MyNavbar />
          {children}
        </div>
      </body>
    </html>
  );
}
